name: Build Latest

on: [push,workflow_dispatch]

env:
  DOTNET_SDK_VERSION: '9.0.*'
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-20.04
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: echo "date=$(date -u -d '8 hours' +'%Y%m%d')" >> "$GITHUB_OUTPUT"

  build-linux-x64-arm64:
    runs-on: ubuntu-20.04
    needs: set-date

    steps:

      # https://learn.microsoft.com/zh-cn/dotnet/core/deploying/native-aot/cross-compile
      - run: |
          sudo apt-get update
          sudo apt-get install -y curl wget libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev clang llvm binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu zlib1g-dev:arm64

      - uses: actions/checkout@v1

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Publish [linux]
        run: |
          dotnet publish BBDown -r linux-x64 -c Release -o artifact

      - name: Package [linux]
        run: |
          cd artifact
          zip ../BBDown_${{ needs.set-date.outputs.date }}_linux-x64.zip BBDown

      - name: Upload Artifact [linux-x64]
        uses: actions/upload-artifact@v4
        with:
          name: BBDown_linux-x64
          path: BBDown_${{ needs.set-date.outputs.date }}_linux-x64.zip
